# from .arxiv_abstract_task import OldArxivTask1
# from .arxiv_algorithm_task import ArxivAlgorithmConfig
# from .arxiv_approch_task import ArxivApproachConfig
# from .arxiv_authors_task import ArxivAuthorsConfig
# from .arxiv_comments_task import ArxivCommentsConfig
# from .arxiv_date_task import ArxivDateConfig
# from .arxiv_implementation_task import ArxivImplementationConfig
# from .arxiv_journal_reference_task import ArxivReferenceConfig
# from .arxiv_problems_task import ArxivProblemsConfig
# from .arxiv_stage_task import ArxivStageConfig
# from .arxiv_topic_task import ArxivTopicConfig
# from .arxiv_website_task import ArxivWebsiteConfig
