from .task_1 import GithubTask1
from .task_2 import GithubTask2
from .task_3 import GithubTask3
from .task_4 import GithubTask4
from .github_create_date_task import OldGithubTask1
from .github_language_task import OldGithubTask2
from .github_stars_task import OldGithubTask3
from .github_commit_task import OldGithubTask4
from .github_watchers_task import OldGithubTask5
from .github_license_task import OldGithubTask6