from .task_1 import GithubTask1
from .task_2 import GithubTask2
from .task_3 import GithubTask3
from .task_4 import GithubTask4
from .github_commit_task import GithubTask5
from .github_create_date_task import GithubTask6
from .github_language_task import GithubTask7
from .github_license_task import GithubTask8
from .github_stars_task import GithubTask9
from .github_watchers_task import GithubTask10
