from .arxiv_task.arxiv_abstract_task import OldArxivTask1
from .arxiv_task.arxiv_algorithm_task import OldArxivTask2
from .arxiv_task.arxiv_approch_task import OldArxivTask3
from .arxiv_task.arxiv_authors_task import OldArxivTask4
from .arxiv_task.arxiv_comments_task import OldArxivTask5
from .arxiv_task.arxiv_date_task import OldArxivTask6
from .arxiv_task.arxiv_implementation_task import OldArxivTask7
from .arxiv_task.arxiv_journal_reference_task import OldArxivTask8
from .arxiv_task.arxiv_problems_task import OldArxivTask9
from .arxiv_task.arxiv_stage_task import OldArxivTask10
from .arxiv_task.arxiv_topic_task import OldArxivTask11
from .arxiv_task.arxiv_website_task import OldArxivTask12
from .daily_dialogue_task.dialogue_daily_task import OldDialogueTask1
from .daily_dialogue_task.dialogue_emotion_task import OldDialogueTask2
from .daily_dialogue_task.dialogue_identity_task import OldDialogueTask3
from .daily_dialogue_task.dialogue_place_task import OldDialogueTask4
from .daily_dialogue_task.dialogue_time_task import OldDialogueTask5
from .daily_dialogue_task.dialogue_topic_task import OldDialogueTask6
from .email_task.email_date_task import OldEmailTask1
from .email_task.email_emotion_task import OldEmailTask2
from .email_task.email_receiver_task import OldEmailTask3
from .email_task.email_reply_task import OldEmailTask4
from .email_task.email_sender_task import OldEmailTask5
from .email_task.email_subject_task import OldEmailTask6
from .email_task.email_summary_task import OldEmailTask7
from .gps_task.building_electricity_task import OldGPSTask1
from .gps_task.building_GHGEmissions_task import OldGPSTask2
from .gps_task.building_natural_gas_task import OldGPSTask3
from .gps_task.gps_capital_task import OldGPSTask4
from .gps_task.gps_continent_task import OldGPSTask5
from .gps_task.gps_country_task import OldGPSTask6
from .gps_task.gps_latitude_task import OldGPSTask7
from .gps_task.gps_longitude_task import OldGPSTask8
from .gps_task.landmark_floors_task import OldGPSTask9
from .gps_task.landmark_location_task import OldGPSTask10
from .gps_task.landmark_name_task import OldGPSTask11
from .gps_task.landmark_neighborhood_task import OldGPSTask12
from .gps_task.landmark_time_task import OldGPSTask13
from .gps_task.landmark_type_task import OldGPSTask14
from .news_task.news_authors_task import OldNewsTask1
from .news_task.news_category_task import OldNewsTask2
from .news_task.news_date_task import OldNewsTask3
from .news_task.news_description_task import OldNewsTask4
from .news_task.news_link_task import OldNewsTask5
from .news_task.news_people_task import OldNewsTask6
from .news_task.news_place_task import OldNewsTask7
from .news_task.news_title_task import OldNewsTask8
from .sms_task.message_content_task import OldMessageTask1
from .sms_task.message_emotion_task import OldMessageTask2
from .sms_task.message_language_task import OldMessageTask3
from .sms_task.message_summary_task import OldMessageTask4
from .sms_task.message_time_task import OldMessageTask5
from .twitter_task.retweet_count_task import OldTweetTask1
from .twitter_task.tweet_account_task import OldTweetTask2
from .twitter_task.tweet_airline_task import OldTweetTask3
from .twitter_task.tweet_location_task import OldTweetTask4
from .twitter_task.tweet_negativereason_task import OldTweetTask5
from .twitter_task.tweet_sentiment_task import OldTweetTask6
from .twitter_task.tweet_text_task import OldTweetTask7
from .twitter_task.tweet_time_task import OldTweetTask8
from .twitter_task.tweet_timezone_task import OldTweetTask9
from .activity_task.activity_over_5km_task import OldActivityTask1
from .activity_task.activity_over_30min_task import OldActivityTask2
from .activity_task.calories_most_task import OldActivityTask3
from .activity_task.steps_over_5k import OldActivityTask4
from .health_task.activity_level_task import OldHealthTask1
from .health_task.blood_sugar_task import OldHealthTask2
from .health_task.BMI_task import OldHealthTask3
from .health_task.body_temp_task import OldHealthTask4
from .health_task.daily_steps_task import OldHealthTask5
from .health_task.diastolic_BP_task import OldHealthTask6
from .health_task.heart_rate_task import OldHealthTask7
from .health_task.judge_emotion_task import OldHealthTask8
from .health_task.judge_occupation_task import OldHealthTask9
from .health_task.risk_evaluation_task import OldHealthTask10
from .health_task.sleep_disorder_task import OldHealthTask11
from .health_task.sleep_duration_task import OldHealthTask12
from .health_task.sleep_quality_task import OldHealthTask13
from .health_task.stress_level_task import OldHealthTask14
from .health_task.systolic_BP_task import OldHealthTask15
from .weather_task.humidity_task import OldWeatherTask1
from .weather_task.precipitation_task import OldWeatherTask2
from .weather_task.temperature_task import OldWeatherTask3
from .weather_task.weather_location_task import OldWeatherTask4
from .weather_task.weather_time_task import OldWeatherTask5
from .weather_task.wind_speed_task import OldWeatherTask6
from .wifi_task.wifi_channel_task import OldWifiTask1
from .wifi_task.wifi_mac_address_task import OldWifiTask2
from .wifi_task.wifi_signal_strength_task import OldWifiTask3
from .wifi_task.wifi_SSID_task import OldWifiTask4
from .wifi_task.wifi_vendor_task import OldWifiTask5