from .task_1 import VideoTask1
from .task_2 import VideoTask2
from .task_3 import VideoTask3
from .task_4 import VideoTask4
from .task_5 import VideoTask5
from .task_6 import VideoTask6
from .task_7 import VideoTask7
from .task_8 import VideoTask8
from .task_9 import VideoTask9