from .task_1 import EmailTaskTest
from .task_2 import MessageStockTask
from .task_4 import WorkReminderTask
from .task_5 import TravelTask
from .task_6 import CatFoodTask
from .task_7 import WaterFlowerTask
from .task_8 import KitchenSafetyTask
from .task_9 import CloseWindowTask
from .task_10 import RemindDriverTask
from .task_11 import StudentInClassTask
from .task_12 import ReadingLightTask
from .task_13 import WaitingRoomTask
from .task_14 import ShopStockTask
from .task_15 import TripMusicTask