from .activity_over_5km_task import ActivityDistanceConfig
from .activity_over_30min_task import ActivityTimeConfig
from .calories_most_task import CaloriesMostConfig
from .steps_over_5k import StepsMostConfig
