from .task_1 import NewsTask1
from .task_2 import NewsTask2
from .task_3 import NewsTask3
from .task_4 import NewsTask4
from .task_5 import NewsTask5
from .news_authors_task import NewsTask6
from .news_category_task import NewsTask7
from .news_date_task import NewsTask8
from .news_description_task import NewsTask9
from .news_link_task import NewsTask10
from .news_people_task import NewsTask11
from .news_place_task import NewsTask12
from .news_title_task import NewsTask13