from .task_1 import GPSTask1
from .task_2 import GPSTask2
from .task_3 import GPSTask3
from .task_4 import WeatherTask1
from .task_5 import WeatherTask2
from .task_6 import WeatherTask3
from .task_7 import WeatherTask4
from .task_8 import HealthTask1
from .task_9 import HealthTask2
from .task_10 import HealthTask3
from .task_11 import HealthTask4
from .task_12 import HealthTask5