from .task_1 import GPSTask1
from .task_2 import GPSTask2
from .task_3 import GPSTask3
from .task_4 import WeatherTask1
from .task_5 import WeatherTask2
from .task_6 import WeatherTask3
from .task_7 import WeatherTask4
from .task_8 import HealthTask1
from .task_9 import HealthTask2
from .task_10 import HealthTask3
from .task_11 import HealthTask4
from .task_12 import HealthTask5
from .gps_capital_task import OldGPSTask4
from .gps_continent_task import OldGPSTask5
from .gps_country_task import OldGPSTask6
from .gps_latitude_task import OldGPSTask7
from .gps_longitude_task import OldGPSTask8
from .landmark_floors_task import OldGPSTask9
from .landmark_location_task import OldGPSTask10
from .landmark_name_task import OldGPSTask11
from .landmark_neighborhood_task import OldGPSTask12
from .landmark_time_task import OldGPSTask13
from .landmark_type_task import OldGPSTask14
from .building_electricity_task import OldGPSTask1
from .building_GHGEmissions_task import OldGPSTask2
from .building_natural_gas_task import OldGPSTask3
from .activity_level_task import OldHealthTask1
from .blood_sugar_task import OldHealthTask2
from .BMI_task import OldHealthTask3
from body_temp_task import OldHealthTask4
from daily_steps_task import OldHealthTask5
from diastolic_BP_task import OldHealthTask6
from heart_rate_task import OldHealthTask7
from judge_emotion_task import OldHealthTask8
from judge_occupation_task import OldHealthTask9
from risk_evaluation_task import OldHealthTask10
from sleep_disorder_task import OldHealthTask11
from sleep_duration_task import OldHealthTask12
from sleep_quality_task import OldHealthTask13
from stress_level_task import OldHealthTask14
from systolic_BP_task import OldHealthTask15
from .humidity_task import OldWeatherTask1
from .precipitation_task import OldWeatherTask2
from .temperature_task import OldWeatherTask3
from .weather_location_task import OldWeatherTask4
from .weather_time_task import OldWeatherTask5
from .wind_speed_task import OldWeatherTask6
from .wifi_channel_task import OldWifiTask1
from .wifi_mac_address_task import OldWifiTask2
from .wifi_signal_strength_task import OldWifiTask3
from .wifi_SSID_task import OldWifiTask4
from .wifi_vendor_task import OldWifiTask5


