from .task_1 import GPSTask1
from .task_2 import GPSTask2
from .task_3 import GPSTask3
from .building_electricity_task import GPSTask4
from .building_GHGEmissions_task import GPSTask5
from .building_natural_gas_task import GPSTask6
from .gps_capital_task import GPSTask7
from .gps_continent_task import GPSTask8
from .gps_country_task import GPSTask9
from .gps_latitude_task import GPSTask10
from .gps_longitude_task import GPSTask11
from .landmark_floors_task import GPSTask12
from .landmark_location_task import GPSTask13
from .landmark_name_task import GPSTask14
from .landmark_neighborhood_task import GPSTask15
from .landmark_time_task import GPSTask16
from .landmark_type_task import GPSTask17
from .task_4 import WeatherTask1
from .task_5 import WeatherTask2
from .task_6 import WeatherTask3
from .task_7 import WeatherTask4
from .humidity_task import WeatherTask5
from .precipitation_task import WeatherTask6
from .temperature_task import WeatherTask7
from .weather_location_task import WeatherTask8
from .weather_time_task import WeatherTask9
from .wind_speed_task import WeatherTask10
from .task_8 import HealthTask1
from .task_9 import HealthTask2
from .task_10 import HealthTask3
from .task_11 import HealthTask4
from .task_12 import HealthTask5
from .activity_level_task import HealthTask6
from .blood_sugar_task import HealthTask7
from .BMI_task import HealthTask8
from .body_temp_task import HealthTask9
from .daily_steps_task import HealthTask10
from .diastolic_BP_task import HealthTask11
from .heart_rate_task import HealthTask12
from .judge_emotion_task import HealthTask13
from .judge_occupation_task import HealthTask14
from .risk_evaluation_task import HealthTask15
from .sleep_disorder_task import HealthTask16
from .sleep_duration_task import HealthTask17
from .sleep_quality_task import HealthTask18
from .stress_level_task import HealthTask19
from .systolic_BP_task import HealthTask20
from .wifi_channel_task import WifiTask1
from .wifi_mac_address_task import WifiTask2
from .wifi_signal_strength_task import WifiTask3
from .wifi_SSID_task import WifiTask4
from .wifi_vendor_task import WifiTask5


