# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import chainstream_bridge_pb2 as chainstream__bridge__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chainstream_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChainStreamBridgeStub(object):
    """ChainStream Bridge Service - 连接Java Agent和Python Runtime
    Python端作为Server，Java端作为Client
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartAgent = channel.unary_unary(
                '/chainstream.ChainStreamBridge/StartAgent',
                request_serializer=chainstream__bridge__pb2.StartAgentRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.StartAgentResponse.FromString,
                _registered_method=True)
        self.StopAgent = channel.unary_unary(
                '/chainstream.ChainStreamBridge/StopAgent',
                request_serializer=chainstream__bridge__pb2.StopAgentRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.StopAgentResponse.FromString,
                _registered_method=True)
        self.CreateStream = channel.unary_unary(
                '/chainstream.ChainStreamBridge/CreateStream',
                request_serializer=chainstream__bridge__pb2.CreateStreamRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.CreateStreamResponse.FromString,
                _registered_method=True)
        self.GetStream = channel.unary_unary(
                '/chainstream.ChainStreamBridge/GetStream',
                request_serializer=chainstream__bridge__pb2.GetStreamRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.GetStreamResponse.FromString,
                _registered_method=True)
        self.AddItem = channel.unary_unary(
                '/chainstream.ChainStreamBridge/AddItem',
                request_serializer=chainstream__bridge__pb2.AddItemRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.AddItemResponse.FromString,
                _registered_method=True)
        self.RegisterStreamListener = channel.unary_unary(
                '/chainstream.ChainStreamBridge/RegisterStreamListener',
                request_serializer=chainstream__bridge__pb2.RegisterStreamListenerRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.RegisterStreamListenerResponse.FromString,
                _registered_method=True)
        self.ForEach = channel.unary_unary(
                '/chainstream.ChainStreamBridge/ForEach',
                request_serializer=chainstream__bridge__pb2.ForEachRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.ForEachResponse.FromString,
                _registered_method=True)
        self.Batch = channel.unary_unary(
                '/chainstream.ChainStreamBridge/Batch',
                request_serializer=chainstream__bridge__pb2.BatchRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.BatchResponse.FromString,
                _registered_method=True)
        self.UnregisterAll = channel.unary_unary(
                '/chainstream.ChainStreamBridge/UnregisterAll',
                request_serializer=chainstream__bridge__pb2.UnregisterAllRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.UnregisterAllResponse.FromString,
                _registered_method=True)
        self.RemoveListener = channel.unary_unary(
                '/chainstream.ChainStreamBridge/RemoveListener',
                request_serializer=chainstream__bridge__pb2.RemoveListenerRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.RemoveListenerResponse.FromString,
                _registered_method=True)
        self.QueryLLM = channel.unary_unary(
                '/chainstream.ChainStreamBridge/QueryLLM',
                request_serializer=chainstream__bridge__pb2.QueryLLMRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.QueryLLMResponse.FromString,
                _registered_method=True)
        self.GetModel = channel.unary_unary(
                '/chainstream.ChainStreamBridge/GetModel',
                request_serializer=chainstream__bridge__pb2.GetModelRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.GetModelResponse.FromString,
                _registered_method=True)
        self.MakePrompt = channel.unary_unary(
                '/chainstream.ChainStreamBridge/MakePrompt',
                request_serializer=chainstream__bridge__pb2.MakePromptRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.MakePromptResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/chainstream.ChainStreamBridge/GetModelInfo',
                request_serializer=chainstream__bridge__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.GetModelInfoResponse.FromString,
                _registered_method=True)
        self.CreateBuffer = channel.unary_unary(
                '/chainstream.ChainStreamBridge/CreateBuffer',
                request_serializer=chainstream__bridge__pb2.CreateBufferRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.CreateBufferResponse.FromString,
                _registered_method=True)
        self.BufferAppend = channel.unary_unary(
                '/chainstream.ChainStreamBridge/BufferAppend',
                request_serializer=chainstream__bridge__pb2.BufferAppendRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.BufferAppendResponse.FromString,
                _registered_method=True)
        self.BufferPop = channel.unary_unary(
                '/chainstream.ChainStreamBridge/BufferPop',
                request_serializer=chainstream__bridge__pb2.BufferPopRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.BufferPopResponse.FromString,
                _registered_method=True)
        self.BufferPopAll = channel.unary_unary(
                '/chainstream.ChainStreamBridge/BufferPopAll',
                request_serializer=chainstream__bridge__pb2.BufferPopAllRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.BufferPopAllResponse.FromString,
                _registered_method=True)
        self.GetRuntimeInfo = channel.unary_unary(
                '/chainstream.ChainStreamBridge/GetRuntimeInfo',
                request_serializer=chainstream__bridge__pb2.GetRuntimeInfoRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.GetRuntimeInfoResponse.FromString,
                _registered_method=True)
        self.ReportAgentId = channel.unary_unary(
                '/chainstream.ChainStreamBridge/ReportAgentId',
                request_serializer=chainstream__bridge__pb2.ReportAgentIdRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.ReportAgentIdResponse.FromString,
                _registered_method=True)


class ChainStreamBridgeServicer(object):
    """ChainStream Bridge Service - 连接Java Agent和Python Runtime
    Python端作为Server，Java端作为Client
    """

    def StartAgent(self, request, context):
        """Agent生命周期管理
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateStream(self, request, context):
        """Stream操作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterStreamListener(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForEach(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Batch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveListener(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryLLM(self, request, context):
        """LLM操作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakePrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBuffer(self, request, context):
        """Buffer操作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BufferAppend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BufferPop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BufferPopAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeInfo(self, request, context):
        """Runtime信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportAgentId(self, request, context):
        """Agent ID报告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChainStreamBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAgent,
                    request_deserializer=chainstream__bridge__pb2.StartAgentRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.StartAgentResponse.SerializeToString,
            ),
            'StopAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAgent,
                    request_deserializer=chainstream__bridge__pb2.StopAgentRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.StopAgentResponse.SerializeToString,
            ),
            'CreateStream': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStream,
                    request_deserializer=chainstream__bridge__pb2.CreateStreamRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.CreateStreamResponse.SerializeToString,
            ),
            'GetStream': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStream,
                    request_deserializer=chainstream__bridge__pb2.GetStreamRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.GetStreamResponse.SerializeToString,
            ),
            'AddItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItem,
                    request_deserializer=chainstream__bridge__pb2.AddItemRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.AddItemResponse.SerializeToString,
            ),
            'RegisterStreamListener': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterStreamListener,
                    request_deserializer=chainstream__bridge__pb2.RegisterStreamListenerRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.RegisterStreamListenerResponse.SerializeToString,
            ),
            'ForEach': grpc.unary_unary_rpc_method_handler(
                    servicer.ForEach,
                    request_deserializer=chainstream__bridge__pb2.ForEachRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.ForEachResponse.SerializeToString,
            ),
            'Batch': grpc.unary_unary_rpc_method_handler(
                    servicer.Batch,
                    request_deserializer=chainstream__bridge__pb2.BatchRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.BatchResponse.SerializeToString,
            ),
            'UnregisterAll': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterAll,
                    request_deserializer=chainstream__bridge__pb2.UnregisterAllRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.UnregisterAllResponse.SerializeToString,
            ),
            'RemoveListener': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveListener,
                    request_deserializer=chainstream__bridge__pb2.RemoveListenerRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.RemoveListenerResponse.SerializeToString,
            ),
            'QueryLLM': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryLLM,
                    request_deserializer=chainstream__bridge__pb2.QueryLLMRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.QueryLLMResponse.SerializeToString,
            ),
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=chainstream__bridge__pb2.GetModelRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.GetModelResponse.SerializeToString,
            ),
            'MakePrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePrompt,
                    request_deserializer=chainstream__bridge__pb2.MakePromptRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.MakePromptResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=chainstream__bridge__pb2.GetModelInfoRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.GetModelInfoResponse.SerializeToString,
            ),
            'CreateBuffer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBuffer,
                    request_deserializer=chainstream__bridge__pb2.CreateBufferRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.CreateBufferResponse.SerializeToString,
            ),
            'BufferAppend': grpc.unary_unary_rpc_method_handler(
                    servicer.BufferAppend,
                    request_deserializer=chainstream__bridge__pb2.BufferAppendRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.BufferAppendResponse.SerializeToString,
            ),
            'BufferPop': grpc.unary_unary_rpc_method_handler(
                    servicer.BufferPop,
                    request_deserializer=chainstream__bridge__pb2.BufferPopRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.BufferPopResponse.SerializeToString,
            ),
            'BufferPopAll': grpc.unary_unary_rpc_method_handler(
                    servicer.BufferPopAll,
                    request_deserializer=chainstream__bridge__pb2.BufferPopAllRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.BufferPopAllResponse.SerializeToString,
            ),
            'GetRuntimeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeInfo,
                    request_deserializer=chainstream__bridge__pb2.GetRuntimeInfoRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.GetRuntimeInfoResponse.SerializeToString,
            ),
            'ReportAgentId': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportAgentId,
                    request_deserializer=chainstream__bridge__pb2.ReportAgentIdRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.ReportAgentIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chainstream.ChainStreamBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chainstream.ChainStreamBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChainStreamBridge(object):
    """ChainStream Bridge Service - 连接Java Agent和Python Runtime
    Python端作为Server，Java端作为Client
    """

    @staticmethod
    def StartAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/StartAgent',
            chainstream__bridge__pb2.StartAgentRequest.SerializeToString,
            chainstream__bridge__pb2.StartAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/StopAgent',
            chainstream__bridge__pb2.StopAgentRequest.SerializeToString,
            chainstream__bridge__pb2.StopAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/CreateStream',
            chainstream__bridge__pb2.CreateStreamRequest.SerializeToString,
            chainstream__bridge__pb2.CreateStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/GetStream',
            chainstream__bridge__pb2.GetStreamRequest.SerializeToString,
            chainstream__bridge__pb2.GetStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/AddItem',
            chainstream__bridge__pb2.AddItemRequest.SerializeToString,
            chainstream__bridge__pb2.AddItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterStreamListener(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/RegisterStreamListener',
            chainstream__bridge__pb2.RegisterStreamListenerRequest.SerializeToString,
            chainstream__bridge__pb2.RegisterStreamListenerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForEach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/ForEach',
            chainstream__bridge__pb2.ForEachRequest.SerializeToString,
            chainstream__bridge__pb2.ForEachResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Batch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/Batch',
            chainstream__bridge__pb2.BatchRequest.SerializeToString,
            chainstream__bridge__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/UnregisterAll',
            chainstream__bridge__pb2.UnregisterAllRequest.SerializeToString,
            chainstream__bridge__pb2.UnregisterAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveListener(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/RemoveListener',
            chainstream__bridge__pb2.RemoveListenerRequest.SerializeToString,
            chainstream__bridge__pb2.RemoveListenerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryLLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/QueryLLM',
            chainstream__bridge__pb2.QueryLLMRequest.SerializeToString,
            chainstream__bridge__pb2.QueryLLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/GetModel',
            chainstream__bridge__pb2.GetModelRequest.SerializeToString,
            chainstream__bridge__pb2.GetModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakePrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/MakePrompt',
            chainstream__bridge__pb2.MakePromptRequest.SerializeToString,
            chainstream__bridge__pb2.MakePromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/GetModelInfo',
            chainstream__bridge__pb2.GetModelInfoRequest.SerializeToString,
            chainstream__bridge__pb2.GetModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBuffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/CreateBuffer',
            chainstream__bridge__pb2.CreateBufferRequest.SerializeToString,
            chainstream__bridge__pb2.CreateBufferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BufferAppend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/BufferAppend',
            chainstream__bridge__pb2.BufferAppendRequest.SerializeToString,
            chainstream__bridge__pb2.BufferAppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BufferPop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/BufferPop',
            chainstream__bridge__pb2.BufferPopRequest.SerializeToString,
            chainstream__bridge__pb2.BufferPopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BufferPopAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/BufferPopAll',
            chainstream__bridge__pb2.BufferPopAllRequest.SerializeToString,
            chainstream__bridge__pb2.BufferPopAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/GetRuntimeInfo',
            chainstream__bridge__pb2.GetRuntimeInfoRequest.SerializeToString,
            chainstream__bridge__pb2.GetRuntimeInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportAgentId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.ChainStreamBridge/ReportAgentId',
            chainstream__bridge__pb2.ReportAgentIdRequest.SerializeToString,
            chainstream__bridge__pb2.ReportAgentIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class JavaAgentCallbackStub(object):
    """Java Agent Callback Service - Java端作为Server，Python端作为Client
    用于Python调用Java的listener函数
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InvokeListener = channel.unary_unary(
                '/chainstream.JavaAgentCallback/InvokeListener',
                request_serializer=chainstream__bridge__pb2.InvokeListenerRequest.SerializeToString,
                response_deserializer=chainstream__bridge__pb2.InvokeListenerResponse.FromString,
                _registered_method=True)


class JavaAgentCallbackServicer(object):
    """Java Agent Callback Service - Java端作为Server，Python端作为Client
    用于Python调用Java的listener函数
    """

    def InvokeListener(self, request, context):
        """调用Java端注册的listener
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JavaAgentCallbackServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InvokeListener': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeListener,
                    request_deserializer=chainstream__bridge__pb2.InvokeListenerRequest.FromString,
                    response_serializer=chainstream__bridge__pb2.InvokeListenerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chainstream.JavaAgentCallback', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chainstream.JavaAgentCallback', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JavaAgentCallback(object):
    """Java Agent Callback Service - Java端作为Server，Python端作为Client
    用于Python调用Java的listener函数
    """

    @staticmethod
    def InvokeListener(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chainstream.JavaAgentCallback/InvokeListener',
            chainstream__bridge__pb2.InvokeListenerRequest.SerializeToString,
            chainstream__bridge__pb2.InvokeListenerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
